export interface ArticleLink {
  title: string;
  url: string;
}

export const articleLinks: ArticleLink[] = [
  { title: "20 Top Lawyers Were Beaten By Legal AI: Here Are Their Surprising Responses", url: "https://hackernoon.com/20-top-lawyers-were-beaten-by-legal-ai-here-are-their-surprising-responses-5dafdf25554d" },
  { title: "A Brief History Of Computer Vision And Convolutional Neural Networks", url: "https://hackernoon.com/a-brief-history-of-computer-vision-and-convolutional-neural-networks-8fe8aacc79f3" },
  { title: "AI Augmented Development: Redefining The Role Of Product Managers", url: "https://hackernoon.com/ai-augmented-development-redefining-the-role-of-product-managers" },
  { title: "AI Chatbots Are Getting Too Good At Making You Say Yes", url: "https://hackernoon.com/ai-chatbots-are-getting-too-good-at-making-you-say-yes" },
  { title: "AI Needs Two Things To Thrive: Trust And Decentralization", url: "https://hackernoon.com/ai-needs-two-things-to-thrive-trust-and-decentralization" },
  { title: "Beyond The Hype: How Small Language Models And Knowledge Graphs Are Redefining Domain-Specific AI", url: "https://hackernoon.com/beyond-the-hype-how-small-language-models-and-knowledge-graphs-are-redefining-domain-specific-ai" },
  { title: "ChatGPT Became The Face Of AI—But The Real Battle Is Building Ecosystems, Not Single Models", url: "https://hackernoon.com/chatgpt-became-the-face-of-aibut-the-real-battle-is-building-ecosystems-not-single-models" },
  { title: "Comments, Naming And Abstractions In The AI Era", url: "https://hackernoon.com/comments-naming-and-abstractions-in-the-ai-era" },
  { title: "Comparing AI Vs Blockchain Hype", url: "https://hackernoon.com/comparing-ai-vs-blockchain-hype" },
  { title: "Decentralized AI: Developing Permissionless Infrastructure Intelligence", url: "https://hackernoon.com/decentralized-ai-developing-permissionless-infrastructure-intelligence" },
  { title: "Decentralized AI: Largest Companies Will Lose The Status Of Monopoly", url: "https://hackernoon.com/decentralized-ai-largest-companies-will-lose-the-status-of-monopoly" },
  { title: "Decentralized AI Summit At MIT Votes OriginTrail As The Best Decentralized AI Project", url: "https://hackernoon.com/decentralized-ai-summit-at-mit-votes-origintrail-as-the-best-decentralized-ai-project" },
  { title: "Decentralized Systems Challenge State Monopoly On Services", url: "https://hackernoon.com/decentralized-systems-challenge-state-monopoly-on-services" },
  { title: "Deep Learning Vs Machine Learning: A Simple Explanation", url: "https://hackernoon.com/deep-learning-vs-machine-learning-a-simple-explanation-47405b3eef08" },
  { title: "DeepSeek Vs ChatGPT Vs Perplexity Vs Qwen Vs Claude Vs DeepMind: More AI Agents And New AI Tools", url: "https://hackernoon.com/deepseek-vs-chatgpt-vs-perplexity-vs-qwen-vs-claude-vs-deepmind-more-ai-agents-and-new-ai-tools" },
  { title: "Elaborate Hoaxes In The Age Of AI", url: "https://hackernoon.com/elaborate-hoaxes-in-the-age-of-ai" },
  { title: "Emerging Tech Companies Must Stop Using Decentralization As An Ideological Gimmick", url: "https://hackernoon.com/emerging-tech-companies-must-stop-using-decentralization-as-an-ideological-gimmick" },
  { title: "Exploring The Open-Source AI Coding Agents Shaping The Future Of Development", url: "https://hackernoon.com/exploring-the-open-source-ai-coding-agents-shaping-the-future-of-development" },
  { title: "From Buttons To Conversations: How Agentic AI Is Redefining System Design", url: "https://hackernoon.com/from-buttons-to-conversations-how-agentic-ai-is-redefining-system-design" },
  { title: "Generative AI: Is It Moving From Large Language Models To Small Language Models", url: "https://hackernoon.com/generative-ai-is-it-moving-from-large-language-models-to-small-languge-models" },
  { title: "Hallucinations Are A Feature Of AI, Humans Are The Bug", url: "https://hackernoon.com/hallucinations-are-a-feature-of-ai-humans-are-the-bug" },
  { title: "How Does DALL-E Mini Work", url: "https://hackernoon.com/how-does-dalle-mini-work" },
  { title: "How Does Human Memory Work", url: "https://hackernoon.com/how-does-human-memory-work" },
  { title: "How Gradient-Free Training Could Decentralize AI", url: "https://hackernoon.com/how-gradient-free-training-could-decentralize-ai" },
  { title: "How The World Will Look Like In 2050", url: "https://hackernoon.com/how-the-world-will-look-like-in-2050-bf12833120de" },
  { title: "How To Run Local LLM AI In Android Studio", url: "https://hackernoon.com/how-to-run-local-llm-ai-in-android-studio" },
  { title: "I Want To Learn Artificial Intelligence And Machine Learning: Where Can I Start", url: "https://hackernoon.com/i-want-to-learn-artificial-intelligence-and-machine-learning-where-can-i-start-7a392a3086ec" },
  { title: "Is AI Actually Writing Production-Ready Code", url: "https://hackernoon.com/is-ai-actually-writing-production-ready-code" },
  { title: "Is Decentralized AI Winning The War Against AI Data Silos", url: "https://hackernoon.com/is-decentralized-ai-winning-the-war-against-ai-data-silos" },
  { title: "Machine Learning: Is The Emperor Wearing Clothes", url: "https://hackernoon.com/machine-learning-is-the-emperor-wearing-clothes-59933d12a3cc" },
  { title: "Mitigating Framing Bias With Polarity Minimization Loss Experiments", url: "https://hackernoon.com/mitigating-framing-bias-with-polarity-minimization-loss-experiments" },
  { title: "Multimodal Is The Most Unappreciated AI Breakthrough, Says DoNotPay CEO Joshua Browder", url: "https://hackernoon.com/multimodal-is-the-most-unappreciated-ai-breakthrough-says-donotpayceo-joshua-browder" },
  { title: "My 44 Favorite Open-Source Solutions For AI Agent Developers", url: "https://hackernoon.com/my-44-favorite-open-source-solutions-for-ai-agent-developers" },
  { title: "New Multi-LLM Strategy Boosts Accuracy In Sentiment Analysis", url: "https://hackernoon.com/new-multi-llm-strategy-boosts-accuracy-in-sentiment-analysis" },
  { title: "Nobel Prize Winner Geoffrey Hinton Explores Two Paths To Intelligence In AI Lecture", url: "https://hackernoon.com/nobel-prize-winner-geoffrey-hinton-explores-two-paths-to-intelligence-in-ai-lecture" },
  { title: "Nuke Silicon Valley, Decentralize AI", url: "https://hackernoon.com/nuke-silicon-valley-decentralize-ai" },
  { title: "Open-Source AI Agent II Takes The Lead In Benchmark Wars—But Is It Truly Autonomous", url: "https://hackernoon.com/open-source-ai-agent-ii-takes-the-lead-in-benchmark-warsbut-is-it-truly-autonomous" },
  { title: "Open-Source AI Is Being Embraced By China And The US", url: "https://hackernoon.com/open-source-ai-is-being-embraced-by-china-and-the-us" },
  { title: "Open-Source: The Next Step In AI Revolution", url: "https://hackernoon.com/open-source-the-next-step-in-ai-revolution" },
  { title: "Our AI Coding Tool Went Viral, Then Everything Broke: This Is What We Learned", url: "https://hackernoon.com/our-ai-coding-tool-went-viral-then-everything-broke-this-is-what-we-learned" },
  { title: "Overcome LLM Hallucinations Using Knowledge Bases", url: "https://hackernoon.com/overcome-llm-hallucinations-using-knowledge-bases" },
  { title: "Small Language Models Beat GPT-4 For Our Use Case: 94% Cost Reduction", url: "https://hackernoon.com/small-language-models-beat-gpt-4-for-our-use-case-94percent-cost-reduction" },
  { title: "So, How Does One Really Determine AI Is Conscious", url: "https://hackernoon.com/so-how-does-one-really-determine-ai-is-conscious" },
  { title: "Standardizing Dataset Documentation To Improve Machine Learning Outcomes", url: "https://hackernoon.com/standardizing-dataset-documentation-to-improve-machine-learning-outcomes" },
  { title: "Startups Of The Year: Meet The AI Industry", url: "https://hackernoon.com/startups-of-the-year-meet-the-ai-industry" },
  { title: "Superintelligence Has The Potential To Begin A New Era Of Personal Empowerment", url: "https://hackernoon.com/superintelligence-has-the-potential-to-begin-a-new-era-of-personal-empowerment" },
  { title: "System Design In The Age Of AI: What Still Requires Human Judgment", url: "https://hackernoon.com/system-design-in-the-age-of-ai-what-still-requires-human-judgment" },
  { title: "TensorFlow Is Dead, Long Live TensorFlow", url: "https://hackernoon.com/tensorflow-is-dead-long-live-tensorflow-49d3e975cf04" },
  { title: "The AI Hierarchy Of Needs", url: "https://hackernoon.com/the-ai-hierarchy-of-needs-18f111fcc007" },
  { title: "The Architecture Of Collaboration: A Practical Framework For Human-AI Interaction", url: "https://hackernoon.com/the-architecture-of-collaboration-a-practical-framework-for-human-ai-interaction" },
  { title: "The Internet Is Worse Than Ever, But We're Too Addicted To Leave", url: "https://hackernoon.com/the-internet-is-worse-than-ever-but-were-too-addicted-to-leave" },
  { title: "The Paradox Of AI: If It Can't Replace Us, Is It Making Us Dumber", url: "https://hackernoon.com/the-paradox-of-ai-if-it-cant-replace-us-is-it-making-us-dumber" },
  { title: "The SaaS Apocalypse And How AI Will Give Birth To One-Person Tech Giants", url: "https://hackernoon.com/the-saas-apocalypse-and-how-ai-will-give-birth-to-one-person-tech-giants" },
  { title: "The Simplest Explanation Of Machine Learning You'll Ever Read", url: "https://hackernoon.com/the-simplest-explanation-of-machine-learning-youll-ever-read-bebc0700047c" },
  { title: "The Truth Nobody Wants To Tell You About AI For Trading", url: "https://hackernoon.com/https-medium-com-supernova-the-truth-nobody-wants-to-tell-you-about-ai-for-trading-5d29a297ee93" },
  { title: "Truth Serum For The AI Age: Factiverse To Fight Fake News And Hallucinations", url: "https://hackernoon.com/truth-serum-for-the-ai-age-factiverse-to-fight-fake-news-and-hallucinations" },
  { title: "What Is A Diffusion LLM And Why Does It Matter", url: "https://hackernoon.com/what-is-a-diffusion-llm-and-why-does-it-matter" },
  { title: "When To Use Small Language Models Over Large Language Models", url: "https://hackernoon.com/when-to-use-small-language-models-over-large-language-models" },
  { title: "Why Businesses Fail At Machine Learning", url: "https://hackernoon.com/why-businesses-fail-at-machine-learning-fbff41c4d5db" },
  { title: "Why Do LLMs Hallucinate", url: "https://hackernoon.com/why-do-llms-hallucinate" },
  { title: "Why I Stopped Letting AI Agents Write Directly To My Database And Built Memstate", url: "https://hackernoon.com/why-i-stopped-letting-ai-agents-write-directly-to-my-database-and-built-memstate" },
  { title: "Why Open Source AI Is Good For Developers Meta And The World", url: "https://hackernoon.com/why-open-source-ai-is-good-for-developers-meta-and-the-world" },
  { title: "Why Salesforce And Microsoft Are Battling For The Future Of AI Agents", url: "https://hackernoon.com/why-salesforce-and-microsoft-are-battling-for-the-future-of-ai-agents" },
  { title: "Will AI Widen Global Inequality", url: "https://hackernoon.com/will-ai-widen-global-inequality" },
];
